INSERT INTO header (table_name, header, description,url, category, detail_header, research, hour, analysed, enabled) VALUES ('klim-tastatur','Klim-Tastatur','','../elektronik/klim-tastatur','Elektronik','Marke;<span class="a-truncate" data-a-word-break="normal" data-a-max-rows="3" data-a-overflow-marker="&amp;hellip;" style="line-height: 1.3em !important; max-height: 3.9em;Artikelgewicht;Batterien enthalten;Hersteller;KLIM',42,31,399,False);
CREATE TABLE `klim-tastatur` (id INT NOT NULL AUTO_INCREMENT, ranking INT(11) NOT NULL,picture VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, main_url VARCHAR(1000) NOT NULL,main_price VARCHAR(255) NOT NULL,second_urls VARCHAR(1000) NOT NULL,second_prices VARCHAR(255) NOT NULL,star FLOAT NOT NULL,review_count INT(11) NOT NULL,highlight INT(11) NOT NULL,detail VARCHAR(1000) NOT NULL,PRIMARY KEY(id));
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (1, '../img/products/Klim-Tastatur/KLIM Domination.webp;', 'KLIM Domination', 'https://www.amazon.de/KLIM-Domination-RGB-QWERTZ-Tastatur-Tastenanschlag-VOLLST%C3%84NDIGE/dp/B01MZINK7U/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2K9M0NPH7QXX&keywords=KLIM+Domination&qid=1667125886&qu=eyJxc2MiOiIxLjI3IiwicXNhIjoiMC40NiIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=logilink+kabelloses+keypad+id0120%2Caps%2C97&sr=8-3', '74,97', 4.3, 604, 1, 'KLIM;1.26 kg;KLIM;PC');
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (2, '../img/products/Klim-Tastatur/KLIM Tandem.webp;', 'KLIM Tandem', 'https://www.amazon.de/KLIM-Tandem-Ergonomisch-Langlebiger-eingebauter/dp/B08LNNLJD6/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2Y3S082RP9BB4&keywords=KLIM+Tandem&qid=1667125892&qu=eyJxc2MiOiIwLjY0IiwicXNhIjoiMC4yNCIsInFzcCI6IjAuMTgifQ%3D%3D&sprefix=klim+domination%2Caps%2C98&sr=8-3', '59,97', 4.3, 165, 0, '-;-;-;-;Schwarz');
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (3, '../img/products/Klim-Tastatur/KLIM Unity Wireless Tastatur und Maus Set.webp;', 'KLIM Unity Wireless Tastatur und Maus Set', 'https://www.amazon.de/KLIM-Unity-Ergonomisch-Langlebiger-eingebauter/dp/B08LNMDXF1/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2UW8EC9QZGAB0&keywords=KLIM+Unity+Wireless+Tastatur+und+Maus+Set&qid=1667125898&sprefix=klim+unity+wireless%2Caps%2C89&sr=8-3', '52,97', 4.2, 198, 0, '-;-;-;-;Schwarz');
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (4, '../img/products/Klim-Tastatur/Klim Dash TKL.webp;', 'Klim Dash TKL', 'https://www.amazon.de/KLIM-Dash-TKL-DE/dp/B082CWP5LB/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=AKOKSXX409EE&keywords=Klim+Dash+TKL&qid=1667125902&qu=eyJxc2MiOiIxLjY5IiwicXNhIjoiMC40OSIsInFzcCI6IjAuNDEifQ%3D%3D&sprefix=klim+unity+wireless+tastatur+und+maus+set%2Caps%2C61&sr=8-3', '69,97', 4.4, 409, 2, 'KLIM;790 g;Nein;KLIM;Laptop, PC');
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (5, '../img/products/Klim-Tastatur/Klim Light V2.webp;', 'Klim Light V2', 'https://www.amazon.de/KLIM-ergonomisch-wasserresistent-Beleuchtete-Integrierter/dp/B085ZMB7JV/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3TS81HNHBVER4&keywords=Klim+Light+V2&qid=1667125908&qu=eyJxc2MiOiIwLjgxIiwicXNhIjoiMC4zMCIsInFzcCI6IjAuNDEifQ%3D%3D&sprefix=klim+dash+tkl%2Caps%2C62&sr=8-3', '39,97', 4.2, 527, 3, 'KLIM;740 g;Nein;KLIM;Spielkonsole, PC');
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (6, '../img/products/Klim-Tastatur/Klim Chroma.webp;', 'Klim Chroma', 'https://www.amazon.de/KLIM-Chroma-Tastatur-QWERTZ-DEUTSCH/dp/B01ICUW9LW/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2MEDJ1FRO7Q9D&keywords=Klim+Chroma&qid=1667125914&qu=eyJxc2MiOiIxLjQwIiwicXNhIjoiMS4wNyIsInFzcCI6IjEuMDcifQ%3D%3D&sprefix=klim+light+v2%2Caps%2C123&sr=8-3', '21,66', 4.4, 3986, 0, 'KLIM;460 g;KLIM;PC');
INSERT INTO `klim-tastatur` (ranking, picture, name, main_url, main_price, star, review_count, highlight,detail) VALUES (7, '../img/products/Klim-Tastatur/KLIM Dash.webp;', 'KLIM Dash', 'https://www.amazon.de/KLIMTM-Dash-Niedrigprofil-Professionelle-Anpassbarkeit/dp/B07HNN8ZW5/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=16QVBB3G4ZP5W&keywords=KLIM+Dash&qid=1667125920&qu=eyJxc2MiOiIyLjM2IiwicXNhIjoiMS44MyIsInFzcCI6IjEuNTYifQ%3D%3D&sprefix=klim+chroma%2Caps%2C97&sr=8-3', '79,97', 4.4, 409, 0, 'KLIM;670 g;KLIM;Laptop, PC');
